const c=document.getElementById('cv'),x=c.getContext('2d'),D=27,G=4,R=270,C=310;
const density=document.getElementById('density'),dv=document.getElementById('dv'),pattern=document.getElementById('pattern');
let dies=[],hover=null;
function positions(){let a=[],s=D+G;for(let y=-9;y<=9;y++)for(let z=-9;z<=9;z++){let px=z*s,py=y*s,r=Math.hypot(px,py);if(r<R-18)a.push({x:px,y:py,r})}return a}
function pick(a,n,p){let out=[];if(p==='random'){a.sort(()=>Math.random()-.5);return a.slice(0,n)}
function w(q){let t=q.reduce((a,b)=>a+b,0),r=Math.random()*t;for(let i=0;i<q.length;i++){r-=q[i];if(r<=0)return i}return q.length-1}
if(p==='center'){while(out.length<n&&a.length){let i=w(a.map(v=>Math.exp(-(v.r/125)**2)+.03));out.push(a.splice(i,1)[0])}}
else if(p==='edge'){while(out.length<n&&a.length){let i=w(a.map(v=>(v.r/(R-18))**4+.03));out.push(a.splice(i,1)[0])}}
else{let cs=[...Array(2+Math.floor(Math.random()*2))].map(()=>{let q=Math.random()*Math.PI*2,r=Math.random()*150;return{x:Math.cos(q)*r,y:Math.sin(q)*r}});while(out.length<n&&a.length){let i=w(a.map(v=>cs.reduce((s,q)=>s+Math.exp(-(Math.hypot(v.x-q.x,v.y-q.y)/80)**2),.015)));out.push(a.splice(i,1)[0])}}return out}
function gen(){let a=positions(),n=Math.round(a.length*+density.value/100),bad=pick([...a],n,pattern.value),set=new Set(bad.map(v=>v.x+','+v.y));dies=a.map((v,i)=>({...v,id:i+1,state:set.has(v.x+','+v.y)?'fail':'pass'}));draw();stats()}
function draw(){x.clearRect(0,0,620,620);x.fillStyle='#0a0f17';x.fillRect(0,0,620,620);x.beginPath();x.arc(C+5,C+7,R+4,0,7);x.fillStyle='#0006';x.fill();x.beginPath();x.arc(C,C,R,0,7);x.fillStyle='#1a222e';x.fill();x.lineWidth=3;x.strokeStyle='#4b5868';x.stroke();dies.forEach(d=>{let px=C+d.x-D/2,py=C+d.y-D/2;x.fillStyle=d.state==='pass'?'#123f2a':'#51202a';x.strokeStyle=d.state==='pass'?'#35c878':'#ef4d5d';x.lineWidth=hover===d.id?3:1.5;x.beginPath();x.roundRect(px,py,D,D,3);x.fill();x.stroke()})}
function stats(){let p=dies.filter(d=>d.state==='pass').length,f=dies.length-p,y=p/(p+f)*100;document.getElementById('passed').textContent=p;document.getElementById('failed').textContent=f;document.getElementById('yield').textContent=y.toFixed(1)+'%';document.getElementById('formula').textContent=`${p} / (${p} + ${f}) × 100 = ${y.toFixed(1)}%`;dv.textContent=density.value+'%';document.getElementById('status').textContent=`${dies.length} dies tested • ${pattern.options[pattern.selectedIndex].text}`}
function pos(e){let r=c.getBoundingClientRect();return{x:(e.clientX-r.left)*620/r.width,y:(e.clientY-r.top)*620/r.height}}
function find(q){return dies.find(d=>{let X=C+d.x,Y=C+d.y;return q.x>=X-D/2&&q.x<=X+D/2&&q.y>=Y-D/2&&q.y<=Y+D/2})}
c.onmousemove=e=>{let d=find(pos(e));hover=d?.id??null;c.style.cursor=d?'pointer':'crosshair';draw()};c.onmouseleave=()=>{hover=null;draw()};c.onclick=e=>{let d=find(pos(e));if(d)document.getElementById('status').textContent=`Die #${d.id}: ${d.state.toUpperCase()}`};
density.oninput=gen;pattern.onchange=gen;document.getElementById('generate').onclick=gen;document.getElementById('reset').onclick=()=>{density.value=19;pattern.value='random';gen()};gen();